import { IRootState } from '../../states';
import { IScreenListResponseItem } from '../../actions/screen';

export const isScreenListLoadingSelector = (state: IRootState) => state.screen.isLoadingScreenList;
export const isScreenListErrorSelector = (state: IRootState) => state.screen.isScreenListError;
export const screenListSelector = (state: IRootState): IScreenListResponseItem[] => state.screen.screenList;
export const screenListTotalItemsSelector = (state: IRootState) => state.screen.totalScreenListItems;
export const screenListCurrentPageSelector = (state: IRootState) => state.screen.currentPage;
export const screenListOffsetSelector = (state: IRootState) => state.screen.offset;
export const screenListItemsToShowSelector = (state: IRootState) => state.screen.itemsToShow;
export const isScreenListAutoUpdateSelector = (state: IRootState) => state.screen.isAutoUpdate;
export const isScreenListActiveSortSelector = (state: IRootState) => state.screen.activeSort;
export const isScreenListActiveSortDirectionSelector = (state: IRootState) => state.screen.activeDirection;
export const getScreenListReportObjectSelector = (state: IRootState) => state.screen.reportObject;
export const getScreenListFirstNameSelector = (state: IRootState) => state.screen.firstName;
export const getScreenListLastNameSelector = (state: IRootState) => state.screen.lastName;
export const getScreenListScreendoxResultIdSelector = (state: IRootState) => state.screen.screeningResultID;
export const getScreenListStartDateSelector = (state: IRootState) => state.screen.startDate;
export const getScreenListEndDateSelector = (state: IRootState) => state.screen.endDate;
export const getScreenListGrpaPeriodKey = (state: IRootState) => state.screen.grpaPeriodKey;
export const getScreenListGrpaPeriodList = (state: IRootState) => state.screen.grpaPeriods;
export const getScreenListLocationList = (state: IRootState) => state.screen.locations;
export const getScreenListSelectedLocationId = (state: IRootState) => state.screen.selectedLocationId;
export const getScreeningID = (state: IRootState): number | null => state.screen.screeningID
export const getScreenListEhrExportPatientInfoSelector = (state: IRootState) => state.screen.EhrExportPatientInfo;
export const isEhrExportPatientInfoSavingLoadingSelector = (state: IRootState) => state.screen.isEhrExportPatientInfoSavingLoading;
export const getScreenListEhrExportPatientRecordsSelector = (state: IRootState) => state.screen.ehrExportPatientRecords;
export const getScreenListEhrExportPatientRecordsCurrentPageSelector = (state: IRootState) => state.screen.ehrExportCurrentPage;
export const getScreenListEhrExportPatientTotatlRecordsSelector = (state: IRootState) => state.screen.ehrExportTotalRecords;
export const isEhrExportPatientRecordsErrorSelector = (state: IRootState) => state.screen.isEhrExportPatientRecordsError;
export const isEhrExportPatientRecordsLoadingSelector = (state: IRootState) => state.screen.isEhrExportPatientRecordsLoading;
export const getEhrExportPatientRecordSelectedIdSelector = (state: IRootState) => state.screen.ehrExportPatientRecordSelectedId;
export const getEhrExportVisitRecordsSelector = (state: IRootState) => state.screen.ehrExportVisitRecords;
export const getEhrExportVisitRecordsCurrentPageSelector = (state: IRootState) => state.screen.ehrExportVisitRecordsCurrentPage;
export const getEhrExportVisitTotalRecordsSelector = (state: IRootState) => state.screen.ehrExportVisitTotalRecords;
export const isEhrExportVisitRecordsLoadingSelector = (state: IRootState) => state.screen.isEhrExportVisitRecordLoading;
export const isEhrExportVisitRecordsErrorSelector = (state: IRootState) => state.screen.isEhrExportVisitRecordError;
export const getEhrExportVisitRecordSelectedIdSelector = (state: IRootState) => state.screen.ehrExportVisitRecordSelectedId;
export const getEhrExportScreeningResultIdSelector = (state: IRootState) => state.screen.ehrExportScreeningResultId;
export const getEhrExportScreeningDateSelector = (state: IRootState) => state.screen.ehrExportScreeningDate;
export const getEhrExportSelectedTabSelector = (state: IRootState) => state.screen.ehrExportSelectedTab;
export const getEhrExportFinalResultsSelector = (state: IRootState) => state.screen.ehrExportFinalResults;
export const isEhrExportFinalResultLoadingSelector = (state: IRootState) => state.screen.ehrExportFinalResultLoading;