//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontDesk.Server.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontDesk.Server.Messages.TextStrings", typeof(TextStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Reports.
        /// </summary>
        public static string BHS_REPORTTYPE_ALL_REPORTS {
            get {
                return ResourceManager.GetString("BHS_REPORTTYPE_ALL_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Reports.
        /// </summary>
        public static string BHS_REPORTTYPE_COMPLETED {
            get {
                return ResourceManager.GetString("BHS_REPORTTYPE_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Reports.
        /// </summary>
        public static string BHS_REPORTTYPE_INCOMPLETE {
            get {
                return ResourceManager.GetString("BHS_REPORTTYPE_INCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result is limited to 1000 rows. Please refine your search criterial to retrieve all matched results..
        /// </summary>
        public static string PDF_LIST_FIRST1000_LIMIT_MESSAGE {
            get {
                return ResourceManager.GetString("PDF_LIST_FIRST1000_LIMIT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Reports.
        /// </summary>
        public static string REPORT_INDICATOR_TYPE_TOTAL_REPORTS {
            get {
                return ResourceManager.GetString("REPORT_INDICATOR_TYPE_TOTAL_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Patients.
        /// </summary>
        public static string REPORT_INDICATOR_TYPE_UNIQUE_PATIENTS {
            get {
                return ResourceManager.GetString("REPORT_INDICATOR_TYPE_UNIQUE_PATIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening result {0} cannot be deleted because it has completed BHS Visit..
        /// </summary>
        public static string SCREENING_RESULT_DELETEFAIL_VISIT_EXISTS {
            get {
                return ResourceManager.GetString("SCREENING_RESULT_DELETEFAIL_VISIT_EXISTS", resourceCulture);
            }
        }
    }
}
