CREATE PROCEDURE dbo.uspUpdateColumbiaSuicideRiskAssessmentReport
    @ColumbiaReportID bigint
    ,@ActualSuicideAttempt bit
    ,@LifetimeActualSuicideAttempt bit
    ,@InterruptedSuicideAttempt bit
    ,@LifetimeInterruptedSuicideAttempt bit
    ,@AbortedSuicideAttempt bit
    ,@LifetimeAbortedSuicideAttempt bit
    ,@OtherPreparatoryActsToKillSelf bit
    ,@LifetimeOtherPreparatoryActsToKillSelf bit
    ,@ActualSelfInjuryBehaviorWithoutSuicideIntent bit
    ,@LifetimeActualSelfInjuryBehaviorWithoutSuicideIntent bit
    ,@WishToBeDead bit
    ,@SuicidalThoughts bit
    ,@SuicidalThoughtsWithMethod bit
    ,@SuicidalIntent bit
    ,@SuicidalIntentWithSpecificPlan bit
    ,@RecentLoss bit
    ,@DescribeRecentLoss nvarchar(max)
    ,@PendingIncarceration bit
    ,@CurrentOrPendingIsolation bit
    ,@Hopelessness bit
    ,@Helplessness bit
    ,@FeelingTrapped bit
    ,@MajorDepressiveEpisode bit
    ,@MixedAffectiveEpisode bit
    ,@CommandHallucinationsToHurtSelf bit
    ,@HighlyImpulsiveBehavior bit
    ,@SubstanceAbuseOrDependence bit
    ,@AgitationOrSevereAnxiety bit
    ,@PerceivedBurdenOnFamilyOrOthers bit
    ,@ChronicPhysicalPain bit
    ,@HomicidalIdeation bit
    ,@AggressiveBehaviorTowardsOthers bit
    ,@MethodForSuicideAvailable bit
    ,@RefusesOrFeelsUnableToAgreeToSafetyPlan bit
    ,@SexualAbuseLifetime bit
    ,@FamilyHistoryOfSuicideLifetime bit
    ,@PreviousPsychiatricDiagnosesAndTreatments bit
    ,@HopelessOrDissatisfiedWithTreatment bit
    ,@NonCompliantWithTreatment bit
    ,@NotReceivingTreatment bit
    ,@IdentifiesReasonsForLiving bit
    ,@ResponsibilityToFamilyOrOthers bit
    ,@SupportiveSocialNetworkOrFamily bit
    ,@FearOfDeathOrDyingDueToPainAndSuffering bit
    ,@BeliefThatSuicideIsImmoral bit
    ,@EngagedInWorkOrSchool bit
    ,@EngagedWithPhoneWorker bit
    ,@DescribeAnySuicidalSelfInjuriousOrAggressiveBehavior nvarchar(max)
AS
UPDATE [dbo].[ColumbiaSuicideRiskAssessmentReport] SET
    ActualSuicideAttempt= @ActualSuicideAttempt
    ,LifetimeActualSuicideAttempt= @LifetimeActualSuicideAttempt
    ,InterruptedSuicideAttempt= @InterruptedSuicideAttempt
    ,LifetimeInterruptedSuicideAttempt= @LifetimeInterruptedSuicideAttempt
    ,AbortedSuicideAttempt= @AbortedSuicideAttempt
    ,LifetimeAbortedSuicideAttempt= @LifetimeAbortedSuicideAttempt
    ,OtherPreparatoryActsToKillSelf= @OtherPreparatoryActsToKillSelf
    ,LifetimeOtherPreparatoryActsToKillSelf= @LifetimeOtherPreparatoryActsToKillSelf
    ,ActualSelfInjuryBehaviorWithoutSuicideIntent= @ActualSelfInjuryBehaviorWithoutSuicideIntent
    ,LifetimeActualSelfInjuryBehaviorWithoutSuicideIntent= @LifetimeActualSelfInjuryBehaviorWithoutSuicideIntent
    ,WishToBeDead= @WishToBeDead
    ,SuicidalThoughts= @SuicidalThoughts
    ,SuicidalThoughtsWithMethod= @SuicidalThoughtsWithMethod
    ,SuicidalIntent= @SuicidalIntent
    ,SuicidalIntentWithSpecificPlan= @SuicidalIntentWithSpecificPlan
    ,RecentLoss= @RecentLoss
    ,DescribeRecentLoss= @DescribeRecentLoss
    ,PendingIncarceration= @PendingIncarceration
    ,CurrentOrPendingIsolation= @CurrentOrPendingIsolation
    ,Hopelessness= @Hopelessness
    ,Helplessness= @Helplessness
    ,FeelingTrapped= @FeelingTrapped
    ,MajorDepressiveEpisode= @MajorDepressiveEpisode
    ,MixedAffectiveEpisode= @MixedAffectiveEpisode
    ,CommandHallucinationsToHurtSelf= @CommandHallucinationsToHurtSelf
    ,HighlyImpulsiveBehavior= @HighlyImpulsiveBehavior
    ,SubstanceAbuseOrDependence= @SubstanceAbuseOrDependence
    ,AgitationOrSevereAnxiety= @AgitationOrSevereAnxiety
    ,PerceivedBurdenOnFamilyOrOthers= @PerceivedBurdenOnFamilyOrOthers
    ,ChronicPhysicalPain= @ChronicPhysicalPain
    ,HomicidalIdeation= @HomicidalIdeation
    ,AggressiveBehaviorTowardsOthers= @AggressiveBehaviorTowardsOthers
    ,MethodForSuicideAvailable= @MethodForSuicideAvailable
    ,RefusesOrFeelsUnableToAgreeToSafetyPlan= @RefusesOrFeelsUnableToAgreeToSafetyPlan
    ,SexualAbuseLifetime= @SexualAbuseLifetime
    ,FamilyHistoryOfSuicideLifetime= @FamilyHistoryOfSuicideLifetime
    ,PreviousPsychiatricDiagnosesAndTreatments= @PreviousPsychiatricDiagnosesAndTreatments
    ,HopelessOrDissatisfiedWithTreatment= @HopelessOrDissatisfiedWithTreatment
    ,NonCompliantWithTreatment= @NonCompliantWithTreatment
    ,NotReceivingTreatment= @NotReceivingTreatment
    ,IdentifiesReasonsForLiving= @IdentifiesReasonsForLiving
    ,ResponsibilityToFamilyOrOthers= @ResponsibilityToFamilyOrOthers
    ,SupportiveSocialNetworkOrFamily= @SupportiveSocialNetworkOrFamily
    ,FearOfDeathOrDyingDueToPainAndSuffering= @FearOfDeathOrDyingDueToPainAndSuffering
    ,BeliefThatSuicideIsImmoral= @BeliefThatSuicideIsImmoral
    ,EngagedInWorkOrSchool= @EngagedInWorkOrSchool
    ,EngagedWithPhoneWorker= @EngagedWithPhoneWorker
    ,DescribeAnySuicidalSelfInjuriousOrAggressiveBehavior= @DescribeAnySuicidalSelfInjuriousOrAggressiveBehavior
WHERE ColumbiaReportID = @ColumbiaReportID

GO

