//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontDesk.Kiosk.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Copyrights {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Copyrights() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontDesk.Kiosk.Resources.Copyrights", typeof(Copyrights).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Center for Responsible Gaming. All rights reserved. Reproduced with permission..
        /// </summary>
        internal static string BBGS {
            get {
                return ResourceManager.GetString("BBGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (CAGE Questionnaire) Copyright © 1984 by the American Medical Association. All rights reserved..
        /// </summary>
        internal static string CAGE {
            get {
                return ResourceManager.GetString("CAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (DAST-10) Copyright © 1982 by Harvey A. Skinner Ph.D. and the 
        ///Centre for Addiction and Mental Health. All rights reserved..
        /// </summary>
        internal static string DAST10 {
            get {
                return ResourceManager.GetString("DAST10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 1999 Pfizer, Inc. All rights reserved. Reproduced with permission..
        /// </summary>
        internal static string GAD7 {
            get {
                return ResourceManager.GetString("GAD7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (HITS) Copyright © 2003 by Kevin M. Sherin, MD, MPH. All rights reserved..
        /// </summary>
        internal static string HITS {
            get {
                return ResourceManager.GetString("HITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (PHQ-9) Copyright © 1999 by Pfizer, Inc. All rights reserved..
        /// </summary>
        internal static string PHQ9 {
            get {
                return ResourceManager.GetString("PHQ9", resourceCulture);
            }
        }
    }
}
