//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontDesk.Kiosk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontDesk.Kiosk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiosk is out of service.  Critical error has occurred..
        /// </summary>
        internal static string CriticalErrorMessage {
            get {
                return ResourceManager.GetString("CriticalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no questionnaire to proceed for screening. Please valid &quot;FrontDeskKiosk.sdf&quot; database file. Please verify validity of database file .
        /// </summary>
        internal static string EmptyQuestionnaireMessage {
            get {
                return ResourceManager.GetString("EmptyQuestionnaireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the server and verify configured Kiosk Key. .
        /// </summary>
        internal static string FailedToVerifyKioskKey {
            get {
                return ResourceManager.GetString("FailedToVerifyKioskKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Kiosk Key &quot;{0}&quot; is not registered on the server. Please ensure that you have entered Kiosk Key value correctly and restart kiosk application..
        /// </summary>
        internal static string InvalidKioskKey {
            get {
                return ResourceManager.GetString("InvalidKioskKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiosk is out of service.
        /// </summary>
        internal static string KioskIsNotInstalledProperlyMessage {
            get {
                return ResourceManager.GetString("KioskIsNotInstalledProperlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiosk is out of service.
        /// </summary>
        internal static string KioskIsOutOfServiceMessage {
            get {
                return ResourceManager.GetString("KioskIsOutOfServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;KioskKey&quot; parameter is not configured. Please set up Kiosk Key before running application..
        /// </summary>
        internal static string MissingKioskKeyMessage {
            get {
                return ResourceManager.GetString("MissingKioskKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth cannot be later than today.
        /// </summary>
        internal static string Validation_BirthdayMoreThanPresentMessage {
            get {
                return ResourceManager.GetString("Validation_BirthdayMoreThanPresentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required.
        /// </summary>
        internal static string Validation_EmptyAddressMessage {
            get {
                return ResourceManager.GetString("Validation_EmptyAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of your birth is required (e.g. 05/10/1982).
        /// </summary>
        internal static string Validation_EmptyBirthdayMessage {
            get {
                return ResourceManager.GetString("Validation_EmptyBirthdayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required.
        /// </summary>
        internal static string Validation_EmptyCityMessage {
            get {
                return ResourceManager.GetString("Validation_EmptyCityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        internal static string Validation_EmptyFirstNameMessage {
            get {
                return ResourceManager.GetString("Validation_EmptyFirstNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        internal static string Validation_EmptyLastNameMessage {
            get {
                return ResourceManager.GetString("Validation_EmptyLastNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        internal static string Validation_EmptyPhoneMessage {
            get {
                return ResourceManager.GetString("Validation_EmptyPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is required.
        /// </summary>
        internal static string Validation_EmptyStateMessage {
            get {
                return ResourceManager.GetString("Validation_EmptyStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid zip code.
        /// </summary>
        internal static string Validation_EmptyZipCodeMessage {
            get {
                return ResourceManager.GetString("Validation_EmptyZipCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date of birth.
        /// </summary>
        internal static string Validation_InvalidBirthdayMessage {
            get {
                return ResourceManager.GetString("Validation_InvalidBirthdayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State \&quot;{0}\&quot; does not exist.
        /// </summary>
        internal static string Validation_InvalidStateMessage {
            get {
                return ResourceManager.GetString("Validation_InvalidStateMessage", resourceCulture);
            }
        }
    }
}
