//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontDesk.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontDesk.Server.Resources.TextMessages", typeof(TextMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string Async_Updating_Text {
            get {
                return ResourceManager.GetString("Async_Updating_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while page content is being updated..
        /// </summary>
        public static string Async_Updating_Wait_Text {
            get {
                return ResourceManager.GetString("Async_Updating_Wait_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates.
        /// </summary>
        public static string BHS_REPORT_INDICATES {
            get {
                return ResourceManager.GetString("BHS_REPORT_INDICATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete {0}. Proceed?.
        /// </summary>
        public static string DeleteConfirmText {
            get {
                return ResourceManager.GetString("DeleteConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Not selected &gt;&gt;.
        /// </summary>
        public static string DropDown_NotSelectedText {
            get {
                return ResourceManager.GetString("DropDown_NotSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Missing].
        /// </summary>
        public static string EmptyButRequiredFiledText {
            get {
                return ResourceManager.GetString("EmptyButRequiredFiledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: ScreenDox record has been already exported on {0}. .
        /// </summary>
        public static string ExportWizard_AlreadyExportedWarning {
            get {
                return ResourceManager.GetString("ExportWizard_AlreadyExportedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annually.
        /// </summary>
        public static string Frequency_Annually {
            get {
                return ResourceManager.GetString("Frequency_Annually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi-Monthly.
        /// </summary>
        public static string Frequency_BiMonthly {
            get {
                return ResourceManager.GetString("Frequency_BiMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Frequency_Daily {
            get {
                return ResourceManager.GetString("Frequency_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every visit.
        /// </summary>
        public static string Frequency_EveryVisit {
            get {
                return ResourceManager.GetString("Frequency_EveryVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Frequency_Monthly {
            get {
                return ResourceManager.GetString("Frequency_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One time only.
        /// </summary>
        public static string Frequency_Once {
            get {
                return ResourceManager.GetString("Frequency_Once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly.
        /// </summary>
        public static string Frequency_Quarterly {
            get {
                return ResourceManager.GetString("Frequency_Quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Frequency_Weekly {
            get {
                return ResourceManager.GetString("Frequency_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data received from kiosk.
        /// </summary>
        public static string InvalidScreeningTraceMsg {
            get {
                return ResourceManager.GetString("InvalidScreeningTraceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening results from Kiosk have been rejected due to application license conflict. Check product activation..
        /// </summary>
        public static string KioskEndpoint_ActivationLicenseErrorMesage {
            get {
                return ResourceManager.GetString("KioskEndpoint_ActivationLicenseErrorMesage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening results from Kiosk have been rejected due to application license conflict. You have more active kiosks than allowed by your license. Please acquire new license or disable unused kiosks..
        /// </summary>
        public static string KioskEndpoint_KioskCountLicenseErrorMesage {
            get {
                return ResourceManager.GetString("KioskEndpoint_KioskCountLicenseErrorMesage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening results have been rejected. Reason: kiosk with KioskID &apos;{0}&apos; has not been found or is disabled. Results have been sent from {1} address..
        /// </summary>
        public static string KioskEndpoint_KioskNotFoundOrDisabled {
            get {
                return ResourceManager.GetString("KioskEndpoint_KioskNotFoundOrDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening results from Kiosk have been rejected due to application license conflict. You have more active branch locations than allowed by your license agreement. Please acquire additional licenses or disable Branch Locations..
        /// </summary>
        public static string KioskEndpoint_LocationCountLicenseErrorMesage {
            get {
                return ResourceManager.GetString("KioskEndpoint_LocationCountLicenseErrorMesage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start working with the application you need to activate it first..
        /// </summary>
        public static string LicenseValidation_NeedToActivateMessage {
            get {
                return ResourceManager.GetString("LicenseValidation_NeedToActivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enable branch location. Maximum branch locations count has been exceeded.
        /// </summary>
        public static string Location_Disabled_Failid {
            get {
                return ResourceManager.GetString("Location_Disabled_Failid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot enable this branch location because you have exceeded the maximum allowed amount of branch locations according to your license..
        /// </summary>
        public static string Location_UnableToEnableBecauseMaxExceeded {
            get {
                return ResourceManager.GetString("Location_UnableToEnableBecauseMaxExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded the maximum allowed number of Branch Locations according to the terms of your license agreement. Please acquire additional licenses or disable Branch Locations..
        /// </summary>
        public static string LocationCountExceeded {
            get {
                return ResourceManager.GetString("LocationCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenDox application need to be activated before first use. You need to login with Superuser credentials to activate this product..
        /// </summary>
        public static string NonSuNeed2ActivateMessage {
            get {
                return ResourceManager.GetString("NonSuNeed2ActivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brief Screening Questions.
        /// </summary>
        public static string REPORT_BHS_HEADER_BRIEF {
            get {
                return ResourceManager.GetString("REPORT_BHS_HEADER_BRIEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined Report requires &quot;Report Type&quot; of “Unique Patients”..
        /// </summary>
        public static string REPORT_EXCEL_COMBINED_REQUIRED_UNIQUE_PATIENTS {
            get {
                return ResourceManager.GetString("REPORT_EXCEL_COMBINED_REQUIRED_UNIQUE_PATIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brief Screening Questions.
        /// </summary>
        public static string REPORT_INDICATOR_HEADER_BRIEF {
            get {
                return ResourceManager.GetString("REPORT_INDICATOR_HEADER_BRIEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (%)   Negative.
        /// </summary>
        public static string REPORT_INDICATOR_HEADER_PERCENT_NEGATIVE {
            get {
                return ResourceManager.GetString("REPORT_INDICATOR_HEADER_PERCENT_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (%)   Positive.
        /// </summary>
        public static string REPORT_INDICATOR_HEADER_PERCENT_POSITIVE {
            get {
                return ResourceManager.GetString("REPORT_INDICATOR_HEADER_PERCENT_POSITIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string REPORT_INDICATOR_HEADER_TOTAL {
            get {
                return ResourceManager.GetString("REPORT_INDICATOR_HEADER_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Negative.
        /// </summary>
        public static string REPORT_INDICATOR_HEADER_TOTAL_NEGATIVE {
            get {
                return ResourceManager.GetString("REPORT_INDICATOR_HEADER_TOTAL_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Positive.
        /// </summary>
        public static string REPORT_INDICATOR_HEADER_TOTAL_POSITIVE {
            get {
                return ResourceManager.GetString("REPORT_INDICATOR_HEADER_TOTAL_POSITIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Reported.
        /// </summary>
        public static string REPORT_INDICATOR_HEADER_TOTAL_REPORTED {
            get {
                return ResourceManager.GetString("REPORT_INDICATOR_HEADER_TOTAL_REPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Unique Patients.
        /// </summary>
        public static string REPORT_INDICATOR_HEADER_TOTAL_UNIQUE {
            get {
                return ResourceManager.GetString("REPORT_INDICATOR_HEADER_TOTAL_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EHR credentials which are required by ScreenDox to export results will expire in {0} day(s). Please contact IT administrator to set up new password..
        /// </summary>
        public static string RPMSCredentialsExpirationAlertMessage {
            get {
                return ResourceManager.GetString("RPMSCredentialsExpirationAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EHR credentials which are required by ScreenDox to export results are expired. The Export feature is disabled. Please contact IT administrator to set up a new password..
        /// </summary>
        public static string RPMSCredentialsExpiredMessage {
            get {
                return ResourceManager.GetString("RPMSCredentialsExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to commit your changes. Proceed?.
        /// </summary>
        public static string SaveChangesConfirmText {
            get {
                return ResourceManager.GetString("SaveChangesConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address is missing.
        /// </summary>
        public static string ScreeningValidation_AddressMissing {
            get {
                return ResourceManager.GetString("ScreeningValidation_AddressMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is missing.
        /// </summary>
        public static string ScreeningValidation_CityMissing {
            get {
                return ResourceManager.GetString("ScreeningValidation_CityMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is missing.
        /// </summary>
        public static string ScreeningValidation_FirstNameMissing {
            get {
                return ResourceManager.GetString("ScreeningValidation_FirstNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        public static string ScreeningValidation_InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("ScreeningValidation_InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid screening result. Please check number of received screening results..
        /// </summary>
        public static string ScreeningValidation_InvalidScreeningResult {
            get {
                return ResourceManager.GetString("ScreeningValidation_InvalidScreeningResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state.
        /// </summary>
        public static string ScreeningValidation_InvalidState {
            get {
                return ResourceManager.GetString("ScreeningValidation_InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ZIP code.
        /// </summary>
        public static string ScreeningValidation_InvalidZipCode {
            get {
                return ResourceManager.GetString("ScreeningValidation_InvalidZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date of birth.
        /// </summary>
        public static string ScreeningValidation_IvalidDateOfBirth {
            get {
                return ResourceManager.GetString("ScreeningValidation_IvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is missing.
        /// </summary>
        public static string ScreeningValidation_LastNameMissing {
            get {
                return ResourceManager.GetString("ScreeningValidation_LastNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is missing.
        /// </summary>
        public static string ScreeningValidation_PhoneMissing {
            get {
                return ResourceManager.GetString("ScreeningValidation_PhoneMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is missing.
        /// </summary>
        public static string ScreeningValidation_StateMissing {
            get {
                return ResourceManager.GetString("ScreeningValidation_StateMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid screening result. Unknown screening tool received: {0}.
        /// </summary>
        public static string ScreeningValidation_UnknownScreeningTool {
            get {
                return ResourceManager.GetString("ScreeningValidation_UnknownScreeningTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP code is missing.
        /// </summary>
        public static string ScreeningValidation_ZipCodeMissing {
            get {
                return ResourceManager.GetString("ScreeningValidation_ZipCodeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New account was activated..
        /// </summary>
        public static string SecurityEvent_AcountActivated {
            get {
                return ResourceManager.GetString("SecurityEvent_AcountActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavioral Health Screening Report was printed. &lt;a href=&quot;{0}&quot;&gt;Report ID: {1}&lt;/a&gt;.
        /// </summary>
        public static string SecurityEvent_BHRPrinted {
            get {
                return ResourceManager.GetString("SecurityEvent_BHRPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavioral Health Screening Report was removed. Patient Name: {0}, Date of Birth: {1}.
        /// </summary>
        public static string SecurityEvent_BHRRemoved {
            get {
                return ResourceManager.GetString("SecurityEvent_BHRRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavioral Health Screening Report was read. &lt;a href=&quot;{0}&quot;&gt;Report ID: {1}&lt;/a&gt;.
        /// </summary>
        public static string SecurityEvent_BHRViewed {
            get {
                return ResourceManager.GetString("SecurityEvent_BHRViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch location &quot;{0}&quot; was removed..
        /// </summary>
        public static string SecurityEvent_BranchRemoved {
            get {
                return ResourceManager.GetString("SecurityEvent_BranchRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient contact information was changed. Screening result ID: {0}.
        /// </summary>
        public static string SecurityEvent_EditPatient {
            get {
                return ResourceManager.GetString("SecurityEvent_EditPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHS Reports has been exported to Excel. Type: {3}. Filter: [Start: {0}, End: {1}. Reports: {2}..
        /// </summary>
        public static string SecurityEvent_ExportBhsReports {
            get {
                return ResourceManager.GetString("SecurityEvent_ExportBhsReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavioral Health Screening Report was exported to external EHR management system. Export details: {0}..
        /// </summary>
        public static string SecurityEvent_ExportedToHealthManagementSystem {
            get {
                return ResourceManager.GetString("SecurityEvent_ExportedToHealthManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiosk &quot;{0}&quot; was removed..
        /// </summary>
        public static string SecurityEvent_KioskRemoved {
            get {
                return ResourceManager.GetString("SecurityEvent_KioskRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavioral Health Screening Report was printed. Report ID: {0}.
        /// </summary>
        public static string SecurityEvent_Local_BHRPrinted {
            get {
                return ResourceManager.GetString("SecurityEvent_Local_BHRPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavioral Health Screening Report was read. Report ID: {0}.
        /// </summary>
        public static string SecurityEvent_Local_BHRViewed {
            get {
                return ResourceManager.GetString("SecurityEvent_Local_BHRViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New branch location was created. Branch Location: {0}.
        /// </summary>
        public static string SecurityEvent_Local_NewBranch {
            get {
                return ResourceManager.GetString("SecurityEvent_Local_NewBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New kiosk was registered. Kiosk: {0}.
        /// </summary>
        public static string SecurityEvent_Local_NewKiosk {
            get {
                return ResourceManager.GetString("SecurityEvent_Local_NewKiosk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user was created. User: {0}.
        /// </summary>
        public static string SecurityEvent_Local_NewUser {
            get {
                return ResourceManager.GetString("SecurityEvent_Local_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was logged into the system..
        /// </summary>
        public static string SecurityEvent_LoggedIn {
            get {
                return ResourceManager.GetString("SecurityEvent_LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient address was updated from RPMS. Patient Name: {0}, Date of Birth: {1}.
        /// </summary>
        public static string SecurityEvent_ManuallyCreateBhsVisitInformation {
            get {
                return ResourceManager.GetString("SecurityEvent_ManuallyCreateBhsVisitInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New branch location was created. Branch Location: &lt;a href=&quot;{0}&quot;&gt;{1}&lt;/a&gt;.
        /// </summary>
        public static string SecurityEvent_NewBranch {
            get {
                return ResourceManager.GetString("SecurityEvent_NewBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New kiosk was registered. Kiosk: &lt;a href=&quot;{0}&quot;&gt;{1}&lt;/a&gt;.
        /// </summary>
        public static string SecurityEvent_NewKiosk {
            get {
                return ResourceManager.GetString("SecurityEvent_NewKiosk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New screening profile was created. Screening Profile &lt;a href=&quot;{0}&quot;&gt;{1}&lt;/a&gt;.
        /// </summary>
        public static string SecurityEvent_NewScreeningProfile {
            get {
                return ResourceManager.GetString("SecurityEvent_NewScreeningProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user was created. User: &lt;a href=&quot;{0}&quot;&gt;{1}&lt;/a&gt;.
        /// </summary>
        public static string SecurityEvent_NewUser {
            get {
                return ResourceManager.GetString("SecurityEvent_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was changed..
        /// </summary>
        public static string SecurityEvent_PasswordChanged {
            get {
                return ResourceManager.GetString("SecurityEvent_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient address was updated from RPMS. Patient Name: {0}, Date of Birth: {1}.
        /// </summary>
        public static string SecurityEvent_PatientAddressHasBeenAddedFromBhsVisit {
            get {
                return ResourceManager.GetString("SecurityEvent_PatientAddressHasBeenAddedFromBhsVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Demographics was printed. ID: {0}.
        /// </summary>
        public static string SecurityEvent_PrintBhsDemographics {
            get {
                return ResourceManager.GetString("SecurityEvent_PrintBhsDemographics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow-Up Report was printed. ID: {0}.
        /// </summary>
        public static string SecurityEvent_PrintBhsFollowUp {
            get {
                return ResourceManager.GetString("SecurityEvent_PrintBhsFollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Report was printed. ID: {0}.
        /// </summary>
        public static string SecurityEvent_PrintBhsVisit {
            get {
                return ResourceManager.GetString("SecurityEvent_PrintBhsVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening profile &quot;{0}&quot; was removed..
        /// </summary>
        public static string SecurityEvent_ScreeningProfileRemoved {
            get {
                return ResourceManager.GetString("SecurityEvent_ScreeningProfileRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security question and answer were changed..
        /// </summary>
        public static string SecurityEvent_SecQuestionChanged {
            get {
                return ResourceManager.GetString("SecurityEvent_SecQuestionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHS Patient Demographics was completed. Report ID: {0},  Patient Name: {1}, Date of Birth: {2}.
        /// </summary>
        public static string SecurityEvent_UpdateBhsDemographicsInformation {
            get {
                return ResourceManager.GetString("SecurityEvent_UpdateBhsDemographicsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHS Follow-Up was completed.Report ID: {0},  Patient Name: {1}, Date of Birth: {2}.
        /// </summary>
        public static string SecurityEvent_UpdateBhsThirtyDayFollowUpInformation {
            get {
                return ResourceManager.GetString("SecurityEvent_UpdateBhsThirtyDayFollowUpInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHS Visit Report was completed. Report ID: {0},  Patient Name: {1}, Date of Birth: {2}.
        /// </summary>
        public static string SecurityEvent_UpdateBhsVisitInformation {
            get {
                return ResourceManager.GetString("SecurityEvent_UpdateBhsVisitInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Use values for Screening Report ID: {0}, Visit ID: {1} has been modified. Old values: Primary: {2}. Secondary: {3}, Tertiary: {4}. New values: Primary: {5}. Secondary: {6}, Tertiary: {7}.
        /// </summary>
        public static string SecurityEvent_UpdateDrugOfChoice {
            get {
                return ResourceManager.GetString("SecurityEvent_UpdateDrugOfChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string SecurityLogExcelCaption_Description {
            get {
                return ResourceManager.GetString("SecurityLogExcelCaption_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string SecurityLogExcelCaption_LogDate {
            get {
                return ResourceManager.GetString("SecurityLogExcelCaption_LogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string SecurityLogExcelCaption_UserName {
            get {
                return ResourceManager.GetString("SecurityLogExcelCaption_UserName", resourceCulture);
            }
        }
    }
}
