CREATE TABLE [dbo].[Roles](
	[Rolename] [varchar](255) NOT NULL,
	CONSTRAINT [PKRoles] PRIMARY KEY CLUSTERED 
	(
		[Rolename] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)
GO
