//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenDox.Server.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenDox.Server.Models.Resources.TextMessages", typeof(TextMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Check-In has been received from Kiosk with errors. Please see the Error Log for detailed information which data is missing. Error entry requires closed date and time on the Check-In record creation date..
        /// </summary>
        internal static string CheckInHasValidationErrors {
            get {
                return ResourceManager.GetString("CheckInHasValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export operation has completed successfully..
        /// </summary>
        internal static string ExportWizard_ExportCompletedSuccessfully {
            get {
                return ResourceManager.GetString("ExportWizard_ExportCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export operation has completed with errors..
        /// </summary>
        internal static string ExportWizard_ExportCompletedWithErrors {
            get {
                return ResourceManager.GetString("ExportWizard_ExportCompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export operation has failed..
        /// </summary>
        internal static string ExportWizard_ExportFailed {
            get {
                return ResourceManager.GetString("ExportWizard_ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set how frequent each screening is conducted for the GPRA period.
        ///&lt;br /&gt;
        ///ScreenDox always screens patient on the first visit of each GPRA period..
        /// </summary>
        internal static string ScreeningFrequency_Notes {
            get {
                return ResourceManager.GetString("ScreeningFrequency_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Minimum Age&apos; field is required. Please enter &quot;0&quot; (zero) value if screening measure should be presented for all patients regardless of their age..
        /// </summary>
        internal static string ScreeningMinimalAgeForm_EmptyValueError {
            get {
                return ResourceManager.GetString("ScreeningMinimalAgeForm_EmptyValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A patient whose age is less than the minimum age for the screening measure will automatically not be presented questions for the measure. &lt;br&gt;Use “0” (zero) value to present the screening measure for all patients..
        /// </summary>
        internal static string ScreeningMinimalAgeForm_Notes {
            get {
                return ResourceManager.GetString("ScreeningMinimalAgeForm_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Minimum Age&apos; field accepts values from 0 to 200.
        /// </summary>
        internal static string ScreeningMinimalAgeForm_RangeError {
            get {
                return ResourceManager.GetString("ScreeningMinimalAgeForm_RangeError", resourceCulture);
            }
        }
    }
}
