//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontDesk.Deployment.SQLServerInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontDesk.Deployment.SQLServerInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation failed. MS SQL Server did not install properly.
        ///Please run MS SQL Server 2008 Express Installation manually to see the detailed error message.
        ///Connection error: {0}.
        /// </summary>
        internal static string Installation_Failed {
            get {
                return ResourceManager.GetString("Installation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Installer 4.5 might not installed properly.  It is required component to install MS SQL Server 2008 Express. Do you want to continue anyway?.
        /// </summary>
        internal static string Installation_MsiMightNotInstallProperly {
            get {
                return ResourceManager.GetString("Installation_MsiMightNotInstallProperly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required component &apos;Microsoft Windows Installer 4.5&apos; for Microsoft SQL Server 2008 Express will be installed. You need to reboot your computer before proceeding with SQL Server Installation..
        /// </summary>
        internal static string Installation_NeedToInstallMsi45 {
            get {
                return ResourceManager.GetString("Installation_NeedToInstallMsi45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required component &apos;Microsoft Powershell v1.0&apos; for Microsoft SQL Server 2008 Express will be installed..
        /// </summary>
        internal static string Installation_NeedToInstallPowershell {
            get {
                return ResourceManager.GetString("Installation_NeedToInstallPowershell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Powershell might not installed properly.  It is required component to install MS SQL Server 2008 Express. Do you want to continue anyway?.
        /// </summary>
        internal static string Installation_PowershellMightNotInstallProperly {
            get {
                return ResourceManager.GetString("Installation_PowershellMightNotInstallProperly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install SQL Server 2008 Express.
        /// </summary>
        internal static string Installation_SQLInstallationFailed {
            get {
                return ResourceManager.GetString("Installation_SQLInstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install SQL Server 2008 Express. Error message: {0}.
        /// </summary>
        internal static string Installation_SQLInstallationFailedWithError {
            get {
                return ResourceManager.GetString("Installation_SQLInstallationFailedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS SQL Server 2008 Express has been installed successfully..
        /// </summary>
        internal static string Installation_Successfull {
            get {
                return ResourceManager.GetString("Installation_Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking connection to the server. Please wait....
        /// </summary>
        internal static string Installation_TestingServerConnection {
            get {
                return ResourceManager.GetString("Installation_TestingServerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install SQL Server 2008 Express SP1.
        /// </summary>
        internal static string InstallationDialog_Title2 {
            get {
                return ResourceManager.GetString("InstallationDialog_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation completed.
        /// </summary>
        internal static string InstallationDialog_Title6 {
            get {
                return ResourceManager.GetString("InstallationDialog_Title6", resourceCulture);
            }
        }
    }
}
