//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontDesk.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontDesk.Server.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Time.
        /// </summary>
        internal static string ScreenTimeLog_AverageTime_Label {
            get {
                return ResourceManager.GetString("ScreenTimeLog_AverageTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anxiety (GAD-2).
        /// </summary>
        internal static string ScreenTimeLog_Gad2_Name {
            get {
                return ResourceManager.GetString("ScreenTimeLog_Gad2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Reports.
        /// </summary>
        internal static string ScreenTimeLog_NumberOfReports_Label {
            get {
                return ResourceManager.GetString("ScreenTimeLog_NumberOfReports_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depression (PHQ-2).
        /// </summary>
        internal static string ScreenTimeLog_Phq2_Name {
            get {
                return ResourceManager.GetString("ScreenTimeLog_Phq2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening Measure.
        /// </summary>
        internal static string ScreenTimeLog_ScreeningMeasure_Label {
            get {
                return ResourceManager.GetString("ScreenTimeLog_ScreeningMeasure_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals for All Screening Measures.
        /// </summary>
        internal static string ScreenTimeLog_Totals_Label {
            get {
                return ResourceManager.GetString("ScreenTimeLog_Totals_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time.
        /// </summary>
        internal static string ScreenTimeLog_TotalTime_Label {
            get {
                return ResourceManager.GetString("ScreenTimeLog_TotalTime_Label", resourceCulture);
            }
        }
    }
}
