-- MATCH PATIENTS

SELECT 
--hr.HEALTH_RECORD_NO,
p.RowId,
vp.NAME,
vp.SEX,
vp.DOB,
st.ABBREVIATION as StateID,
vp.MAILING_ADDRESSCITY as City,
vp.MAILING_ADDRESSZIP as ZipCode,
vp.MAILING_ADDRESSSTREET + ' ' + vp.STREET_ADDRESS_LINE_2 + ' ' + vp.STREET_ADDRESS_LINE_3 AS StreetAddress,
vp.HOME_PHONE,
vp.OFFICE_PHONE,
vp.PHONE_3,
vp.PHONE_4
FROM IHS.PATIENT p 
--INNER JOIN IHS.SUB_HEALTH_RECORD_NO_  hr ON hr.Patient = p.RowId
INNER JOIN IHS.VA_PATIENT vp ON p.NAME = vp.RowID
INNER JOIN IHS.STATE st ON st.RowId= vp.MAILING_ADDRESSSTATE
WHERE vp.Name = 'ANDERSON,TERESA'



-----
-- duplicates
select p1.Name
from IHS.VA_PATIENT p1 INNER JOIN IHS.VA_PATIENT p2 ON p1.RowId > p2.RowId and p1.Name = p2.Name


----------
SELECT 
p.RowId,
vp.RowId,
vp.NAME,
vp.SEX,
vp.DOB,
vp.SSN,
vp.MAILING_ADDRESSSTREET,
vp.STREET_ADDRESS_LINE_2,
vp.STREET_ADDRESS_LINE_3,
vp.MAILING_ADDRESSCITY,
vp.MAILING_ADDRESSZIP,
vp.HOME_PHONE,
vp.OFFICE_PHONE,
vp.PHONE_3,
vp.PHONE_4
FROM IHS.PATIENT p INNER JOIN IHS.VA_PATIENT vp ON p.NAME = vp.RowID

SELECT 
p.RowId,
vp.RowId,
vp.NAME,
vp.SEX,
vp.DOB,
vp.SSN,
vp.MAILING_ADDRESSSTREET,
vp.STREET_ADDRESS_LINE_2,
vp.STREET_ADDRESS_LINE_3,
vp.MAILING_ADDRESSCITY,
vp.MAILING_ADDRESSZIP,
vp.HOME_PHONE,
vp.OFFICE_PHONE,
vp.PHONE_3,
vp.PHONE_4
FROM IHS.PATIENT p INNER JOIN IHS.VA_PATIENT vp ON p.NAME = vp.RowID




SELECT 
hr.HEALTH_RECORD_NO,
vp.NAME,
vp.SEX,
vp.DOB,
vp.STATE,
vp.SSN,
vp.MAILING_ADDRESSSTREET,
vp.STREET_ADDRESS_LINE_2,
vp.STREET_ADDRESS_LINE_3,
vp.MAILING_ADDRESSCITY,
vp.MAILING_ADDRESSZIP,
vp.HOME_PHONE,
vp.OFFICE_PHONE,
vp.PHONE_3,
vp.PHONE_4
FROM IHS.PATIENT p 
INNER JOIN IHS.SUB_HEALTH_RECORD_NO_  hr ON hr.Patient = p.RowId
INNER JOIN IHS.VA_PATIENT vp ON p.NAME = vp.RowID;


SELECT * FROM IHS.STATE;
