SELECT 
vz.RowId as VisitID,
vz.VISITADMIT_DATETIME,
vz.SERVICE_CATEGORY,
vz.PATIENT_NAME as PatientID,
vp.Name as PatientName,
vz.LOC_OF_ENCOUNTER as LocationID,
inst.Name as LocationName
FROM IHS.VISIT vz 
INNER JOIN IHS.Patient p ON p.RowId = vz.PATIENT_NAME
INNER JOIN IHS.VA_PATIENT vp ON vp.RowId = p.Name
INNER JOIN IHS.LOCATION loc ON loc.RowId  = vz.LOC_OF_ENCOUNTER
INNER JOIN IHS.INSTITUTION inst ON inst.RowId = loc.Name
where vp.RowId = 2 and inst.Name = '2010 DEMO INDIAN HOSPITAL'
order by vz.VISITADMIT_DATETIME DESC

/*

IHS.VISIT
property TYPE as Fileman.String(DISPLAYLIST=",IHS,CONTRACT,TRIBE-NON 638/NON-COMPACT,OTHER,TRIBE-638 PROGRAM,VA,TRIBE-COMPACTED TRIBAL PROGRAM,URBAN CLINIC,STATE",MAXLEN=30,SELECTIVITY="10.0000%",VALUELIST=",I,C,T,O,6,V,P,U,S"); 

property SERVICECATEGORY as Fileman.String(DISPLAYLIST=",AMBULATORY,HOSPITALIZATION,IN HOSPITAL,CHART REVIEW,TELECOMMUNICATIONS,NOT FOUND,DAY SURGERY,OBSERVATION,EVENT (HISTORICAL),NURSING HOME,DAILY HOSPITALIZATION DATA,ANCILLARY PACKAGE DAILY DATA",MAXLEN=28,SELECTIVITY="8.3333%",VALUELIST=",A,H,I,C,T,N,S,O,E,R,D,X") [ SqlFieldName = SERVICE_CATEGORY,Required ]; 
Field Name: SERVICE_CATEGORY FileMan Field#: .07 SERVICE_CATEGORY 



*/