//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenDox.EHR.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenDox.EHR.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answered No on question {0}. .
        /// </summary>
        public static string AnsweredNoOnTemplate1 {
            get {
                return ResourceManager.GetString("AnsweredNoOnTemplate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answered Yes on question {0}..
        /// </summary>
        public static string AnsweredYesOnTemplate {
            get {
                return ResourceManager.GetString("AnsweredYesOnTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation of input parameters.
        /// </summary>
        public static string CommitExport_DataValidationActionName {
            get {
                return ResourceManager.GetString("CommitExport_DataValidationActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create crisis alert(s).
        /// </summary>
        public static string CommitExport_InsertCrisisAlertActionName {
            get {
                return ResourceManager.GetString("CommitExport_InsertCrisisAlertActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create exam(s).
        /// </summary>
        public static string CommitExport_InsertExamActionName {
            get {
                return ResourceManager.GetString("CommitExport_InsertExamActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create health factor(s).
        /// </summary>
        public static string CommitExport_InsertHealthFactorActionName {
            get {
                return ResourceManager.GetString("CommitExport_InsertHealthFactorActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient record update operation did not affect any record. Record fields have been changed by another user and update operation failed. Please update patient fields manually..
        /// </summary>
        public static string CommitExport_PatientRecordUpdateNoAffectedRowsError {
            get {
                return ResourceManager.GetString("CommitExport_PatientRecordUpdateNoAffectedRowsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export patient screenings result.
        /// </summary>
        public static string CommitExport_ScreeningDataActionName {
            get {
                return ResourceManager.GetString("CommitExport_ScreeningDataActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export operation for patient screening report has failed. Please try again later. If problem repeats, please contact technical support team..
        /// </summary>
        public static string CommitExport_ScreeningDataExportError {
            get {
                return ResourceManager.GetString("CommitExport_ScreeningDataExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update patient record.
        /// </summary>
        public static string CommitExport_UpdatePatientActionName {
            get {
                return ResourceManager.GetString("CommitExport_UpdatePatientActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient answered &quot;{0}&quot; to &quot;Over the LAST 2 WEEKS, how often have you been bothered by any of the following problems? Thoughts that you would be better off dead or of hurting yourself in some way.&quot;.
        /// </summary>
        public static string DepressionCrisisAlertDetailsTemplate {
            get {
                return ResourceManager.GetString("DepressionCrisisAlertDetailsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score: {0}. Level of Risk: {1}. Exported from Screendox..
        /// </summary>
        public static string ExamCommentTemplate {
            get {
                return ResourceManager.GetString("ExamCommentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score: {0}. Level of Risk: SUICIDAL ideation + {1}. Exported from Screendox..
        /// </summary>
        public static string ExamSuicidalCommentTemplate {
            get {
                return ResourceManager.GetString("ExamSuicidalCommentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported from Screendox..
        /// </summary>
        public static string HealthFactorCommentTemplate {
            get {
                return ResourceManager.GetString("HealthFactorCommentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient answered &quot;{0}&quot; to: &quot;Over the LAST 12 MONTHS, how often did your partner, family member, or caregiver Physically HURT you?&quot;.
        /// </summary>
        public static string PartnerViolenceCrisisAlertDetailsTemplate {
            get {
                return ResourceManager.GetString("PartnerViolenceCrisisAlertDetailsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded max length for {0} field in EHR Patient record. Max. length is {1}. New value &apos;{2}&apos;  has length of {3} characters. Please shrink the field value to update patient&apos;s record..
        /// </summary>
        public static string PatientExceededStringFieldLengthTemplate {
            get {
                return ResourceManager.GetString("PatientExceededStringFieldLengthTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient record not found in the EHR System..
        /// </summary>
        public static string PatientRecordNotFound {
            get {
                return ResourceManager.GetString("PatientRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenDox.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State name is empty and cannot be exported..
        /// </summary>
        public static string StateNameIsEmpty {
            get {
                return ResourceManager.GetString("StateNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit not found in the EHR..
        /// </summary>
        public static string VisitNotFound {
            get {
                return ResourceManager.GetString("VisitNotFound", resourceCulture);
            }
        }
    }
}
