//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontDesk.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScreeningLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScreeningLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontDesk.Common.Resources.ScreeningLabels", typeof(ScreeningLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anxiety (GAD-2).
        /// </summary>
        public static string Screening_Report_Section_GAD2 {
            get {
                return ResourceManager.GetString("Screening_Report_Section_GAD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anxiety (GAD-7).
        /// </summary>
        public static string Screening_Report_Section_GAD7 {
            get {
                return ResourceManager.GetString("Screening_Report_Section_GAD7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAD-2.
        /// </summary>
        public static string Screening_Report_Section_ID_GAD2 {
            get {
                return ResourceManager.GetString("Screening_Report_Section_ID_GAD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAD-7.
        /// </summary>
        public static string Screening_Report_Section_ID_GAD7 {
            get {
                return ResourceManager.GetString("Screening_Report_Section_ID_GAD7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHQ-2.
        /// </summary>
        public static string Screening_Report_Section_ID_PHQ2 {
            get {
                return ResourceManager.GetString("Screening_Report_Section_ID_PHQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHQ-9.
        /// </summary>
        public static string Screening_Report_Section_ID_PHQ9 {
            get {
                return ResourceManager.GetString("Screening_Report_Section_ID_PHQ9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depression (PHQ-2).
        /// </summary>
        public static string Screening_Report_Section_PHQ2 {
            get {
                return ResourceManager.GetString("Screening_Report_Section_PHQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depression (PHQ-9).
        /// </summary>
        public static string Screening_Report_Section_PHQ9 {
            get {
                return ResourceManager.GetString("Screening_Report_Section_PHQ9", resourceCulture);
            }
        }
    }
}
