//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontDesk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontDesk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcohol Use (CAGE).
        /// </summary>
        public static string ScreeningFrequency_Alcohol_Name {
            get {
                return ResourceManager.GetString("ScreeningFrequency_Alcohol_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anxiety (GAD-2/GAD-7).
        /// </summary>
        public static string ScreeningFrequency_Anxiety_Name {
            get {
                return ResourceManager.GetString("ScreeningFrequency_Anxiety_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ScreeningFrequency_Contact_Name {
            get {
                return ResourceManager.GetString("ScreeningFrequency_Contact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Demographics.
        /// </summary>
        public static string ScreeningFrequency_Demographics_Name {
            get {
                return ResourceManager.GetString("ScreeningFrequency_Demographics_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depression (PHQ-2/PHQ-9).
        /// </summary>
        public static string ScreeningFrequency_Depression_Name {
            get {
                return ResourceManager.GetString("ScreeningFrequency_Depression_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency is the number of months in GPRA period.
        /// </summary>
        public static string ScreeningFrequency_FrequencyValidationError {
            get {
                return ResourceManager.GetString("ScreeningFrequency_FrequencyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anxiety (GAD-7).
        /// </summary>
        public static string ScreeningFrequency_GAD7A_Name {
            get {
                return ResourceManager.GetString("ScreeningFrequency_GAD7A_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intimate Partner/Domestic Violence (HITS).
        /// </summary>
        public static string ScreeningFrequency_PartnerViolence_Name {
            get {
                return ResourceManager.GetString("ScreeningFrequency_PartnerViolence_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depression (PHQ-9).
        /// </summary>
        public static string ScreeningFrequency_PHQ9A_Name {
            get {
                return ResourceManager.GetString("ScreeningFrequency_PHQ9A_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Gambling (BBGS).
        /// </summary>
        public static string ScreeningFrequency_ProblemGambling_Name {
            get {
                return ResourceManager.GetString("ScreeningFrequency_ProblemGambling_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening Frequency.
        /// </summary>
        public static string ScreeningFrequency_Screening_Name {
            get {
                return ResourceManager.GetString("ScreeningFrequency_Screening_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoker in the Home.
        /// </summary>
        public static string ScreeningFrequency_SmokerInHome_Name {
            get {
                return ResourceManager.GetString("ScreeningFrequency_SmokerInHome_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Medical Drug Use (DAST-10).
        /// </summary>
        public static string ScreeningFrequency_SubstanceAbuse_Name {
            get {
                return ResourceManager.GetString("ScreeningFrequency_SubstanceAbuse_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobacco Use.
        /// </summary>
        public static string ScreeningFrequency_Tobacco_Name {
            get {
                return ResourceManager.GetString("ScreeningFrequency_Tobacco_Name", resourceCulture);
            }
        }
    }
}
