//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontDesk.Deploy.Server.Actions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontDesk.Deploy.Server.Actions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create security certificate.
        /// </summary>
        internal static string CertificateCreationError {
            get {
                return ResourceManager.GetString("CertificateCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; folder already contains one or more ScreenDox certificates that can be used for kiosks authentification. Do you want to replace them?.
        /// </summary>
        internal static string CertificateExistsMessage {
            get {
                return ResourceManager.GetString("CertificateExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system already has installed ScreenDox certificate that can be used for kiosks authentication. Do you want to replace it?.
        /// </summary>
        internal static string CertificateInstalledMessage {
            get {
                return ResourceManager.GetString("CertificateInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Kiosks Authentication.
        /// </summary>
        internal static string ConfigureKiosksAuthenticationTitle {
            get {
                return ResourceManager.GetString("ConfigureKiosksAuthenticationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fd_install_banner {
            get {
                object obj = ResourceManager.GetObject("fd_install_banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([a-zA-Z]:)(\\(\w[\w ]*)).
        /// </summary>
        internal static string FolderPathRegexp {
            get {
                return ResourceManager.GetString("FolderPathRegexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation aborted.
        /// </summary>
        internal static string Installation_Aborted {
            get {
                return ResourceManager.GetString("Installation_Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install ScreenDox Screener Server. Error message: {0}.
        /// </summary>
        internal static string Installation_Failed {
            get {
                return ResourceManager.GetString("Installation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install SQL Server 2008 Express.
        /// </summary>
        internal static string Installation_SQLInstallationFailed {
            get {
                return ResourceManager.GetString("Installation_SQLInstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of SQL Server 2008 Express SP1.
        /// </summary>
        internal static string InstallationDialog_Title2 {
            get {
                return ResourceManager.GetString("InstallationDialog_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application connection settings.
        /// </summary>
        internal static string InstallationDialog_Title3 {
            get {
                return ResourceManager.GetString("InstallationDialog_Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating ScreenDox Database.
        /// </summary>
        internal static string InstallationDialog_Title4 {
            get {
                return ResourceManager.GetString("InstallationDialog_Title4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenDox Installation Message.
        /// </summary>
        internal static string InstallationMessageCaption {
            get {
                return ResourceManager.GetString("InstallationMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Security Certificates.
        /// </summary>
        internal static string InstallingCertificates {
            get {
                return ResourceManager.GetString("InstallingCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid folder for security certificate..
        /// </summary>
        internal static string InvalidCertificateFolder {
            get {
                return ResourceManager.GetString("InvalidCertificateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure auto-login settings on windows startup.
        /// </summary>
        internal static string KioskAutoLogonStepTitle {
            get {
                return ResourceManager.GetString("KioskAutoLogonStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Database Server.
        /// </summary>
        internal static string SelectDatabaseServer {
            get {
                return ResourceManager.GetString("SelectDatabaseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure a Secure Connection.
        /// </summary>
        internal static string SetupSSL {
            get {
                return ResourceManager.GetString("SetupSSL", resourceCulture);
            }
        }
    }
}
